spring.application.name=secureFileShare
spring.datasource.url=jdbc:mysql://localhost:3306/securefiles?useSSL=false&serverTimezone=UTC
spring.datasource.username=springuser
spring.datasource.password=majid1992

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
